[2016-11-27 12:01:13] DEBUG [django.db.backends:90] (0.004) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 12:01:13] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 14:43:36] DEBUG [django.db.backends:90] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 14:43:36] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 14:45:37] INFO [django.server:131] "GET /admin HTTP/1.1" 301 0
[2016-11-27 14:45:38] DEBUG [django.db.backends:90] (0.009) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'figcln8g3oukkwuqylv6c0gc2bcu7o51' AND "django_session"."expire_date" > '2016-11-27 22:45:38.160215'); args=('figcln8g3oukkwuqylv6c0gc2bcu7o51', '2016-11-27 22:45:38.160215')
[2016-11-27 14:45:38] DEBUG [django.db.backends:90] (0.001) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."id" = '915b008a06b9406391807ca522830fca'; args=('915b008a06b9406391807ca522830fca',)
[2016-11-27 14:45:38] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'False': False, 'None': None}, {'request': <WSGIRequest: GET '/admin/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000121A9BC3128>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'INFO': 20, 'SUCCESS': 25, 'ERROR': 40, 'DEBUG': 10}, 'user': <SimpleLazyObject: <User: admin>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x00000121A9F01EA0>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00000121A9FE1B00>}, {}, {'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D0BD68>, 'app_list': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8C7A630>, 'app_url': '/admin/auth/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F730B8>, 'object_name': 'Group', 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20128>, 'object_name': 'Permission', 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F14FD0>, 'object_name': 'HierarchyType', 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A99742E8>, 'object_name': 'Hierarchy', 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37C50>, 'object_name': 'Menu', 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9974320>, 'object_name': 'Person', 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20400>, 'object_name': 'UserHierarchyGroup', 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F73128>, 'object_name': 'UserHierarchyPermission', 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F14C88>, 'object_name': 'User', 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D1C9E8>, 'app_url': '/admin/contenttypes/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20668>, 'object_name': 'ContentType', 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F205F8>, 'object_name': 'AccessToken', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20320>, 'object_name': 'Application', 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20358>, 'object_name': 'Grant', 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F206D8>, 'object_name': 'RefreshToken', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'has_module_perms': True, 'app_label': 'registro', 'name': 'Registro', 'app_url': '/admin/registro/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': 'Clientes', 'object_name': 'Cliente', 'admin_url': '/admin/registro/cliente/', 'add_url': '/admin/registro/cliente/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9E4AF28>, 'object_name': 'Distribuidor', 'admin_url': '/admin/registro/distribuidor/', 'add_url': '/admin/registro/distribuidor/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F208D0>, 'object_name': 'Marca', 'admin_url': '/admin/registro/marca/', 'add_url': '/admin/registro/marca/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F205C0>, 'object_name': 'Producto', 'admin_url': '/admin/registro/producto/', 'add_url': '/admin/registro/producto/add/'}]}], 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D03B38>, 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D03A90>, 'has_permission': True, 'available_apps': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8C7A630>, 'app_url': '/admin/auth/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37940>, 'object_name': 'Group', 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37978>, 'object_name': 'Permission', 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F580F0>, 'object_name': 'HierarchyType', 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37A90>, 'object_name': 'Hierarchy', 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58828>, 'object_name': 'Menu', 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37C88>, 'object_name': 'Person', 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F584A8>, 'object_name': 'UserHierarchyGroup', 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F379E8>, 'object_name': 'UserHierarchyPermission', 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58198>, 'object_name': 'User', 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D1C9E8>, 'app_url': '/admin/contenttypes/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58DA0>, 'object_name': 'ContentType', 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37D68>, 'object_name': 'AccessToken', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58B00>, 'object_name': 'Application', 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F379B0>, 'object_name': 'Grant', 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37908>, 'object_name': 'RefreshToken', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'has_module_perms': True, 'app_label': 'registro', 'name': 'Registro', 'app_url': '/admin/registro/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': 'Clientes', 'object_name': 'Cliente', 'admin_url': '/admin/registro/cliente/', 'add_url': '/admin/registro/cliente/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58AC8>, 'object_name': 'Distribuidor', 'admin_url': '/admin/registro/distribuidor/', 'add_url': '/admin/registro/distribuidor/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37F98>, 'object_name': 'Marca', 'admin_url': '/admin/registro/marca/', 'add_url': '/admin/registro/marca/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58550>, 'object_name': 'Producto', 'admin_url': '/admin/registro/producto/', 'add_url': '/admin/registro/producto/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'site_url': '/', 'LANGUAGE_BIDI': False}]"
[2016-11-27 14:45:38] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'False': False, 'None': None}, {'request': <WSGIRequest: GET '/admin/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000121A9BC3128>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'INFO': 20, 'SUCCESS': 25, 'ERROR': 40, 'DEBUG': 10}, 'user': <SimpleLazyObject: <User: admin>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x00000121A9F01EA0>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00000121A9FE1B00>}, {}, {'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D0BD68>, 'app_list': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8C7A630>, 'app_url': '/admin/auth/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F730B8>, 'object_name': 'Group', 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20128>, 'object_name': 'Permission', 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F14FD0>, 'object_name': 'HierarchyType', 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A99742E8>, 'object_name': 'Hierarchy', 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37C50>, 'object_name': 'Menu', 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9974320>, 'object_name': 'Person', 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20400>, 'object_name': 'UserHierarchyGroup', 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F73128>, 'object_name': 'UserHierarchyPermission', 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F14C88>, 'object_name': 'User', 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D1C9E8>, 'app_url': '/admin/contenttypes/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20668>, 'object_name': 'ContentType', 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F205F8>, 'object_name': 'AccessToken', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20320>, 'object_name': 'Application', 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F20358>, 'object_name': 'Grant', 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F206D8>, 'object_name': 'RefreshToken', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'has_module_perms': True, 'app_label': 'registro', 'name': 'Registro', 'app_url': '/admin/registro/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': 'Clientes', 'object_name': 'Cliente', 'admin_url': '/admin/registro/cliente/', 'add_url': '/admin/registro/cliente/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9E4AF28>, 'object_name': 'Distribuidor', 'admin_url': '/admin/registro/distribuidor/', 'add_url': '/admin/registro/distribuidor/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F208D0>, 'object_name': 'Marca', 'admin_url': '/admin/registro/marca/', 'add_url': '/admin/registro/marca/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F205C0>, 'object_name': 'Producto', 'admin_url': '/admin/registro/producto/', 'add_url': '/admin/registro/producto/add/'}]}], 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D03B38>, 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D03A90>, 'has_permission': True, 'available_apps': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8C7A630>, 'app_url': '/admin/auth/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37940>, 'object_name': 'Group', 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37978>, 'object_name': 'Permission', 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F580F0>, 'object_name': 'HierarchyType', 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37A90>, 'object_name': 'Hierarchy', 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58828>, 'object_name': 'Menu', 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37C88>, 'object_name': 'Person', 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F584A8>, 'object_name': 'UserHierarchyGroup', 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F379E8>, 'object_name': 'UserHierarchyPermission', 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58198>, 'object_name': 'User', 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D1C9E8>, 'app_url': '/admin/contenttypes/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58DA0>, 'object_name': 'ContentType', 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37D68>, 'object_name': 'AccessToken', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58B00>, 'object_name': 'Application', 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F379B0>, 'object_name': 'Grant', 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37908>, 'object_name': 'RefreshToken', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'has_module_perms': True, 'app_label': 'registro', 'name': 'Registro', 'app_url': '/admin/registro/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': 'Clientes', 'object_name': 'Cliente', 'admin_url': '/admin/registro/cliente/', 'add_url': '/admin/registro/cliente/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58AC8>, 'object_name': 'Distribuidor', 'admin_url': '/admin/registro/distribuidor/', 'add_url': '/admin/registro/distribuidor/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F37F98>, 'object_name': 'Marca', 'admin_url': '/admin/registro/marca/', 'add_url': '/admin/registro/marca/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9F58550>, 'object_name': 'Producto', 'admin_url': '/admin/registro/producto/', 'add_url': '/admin/registro/producto/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'site_url': '/', 'LANGUAGE_BIDI': False}]"
[2016-11-27 14:45:38] DEBUG [django.db.backends:90] (0.001) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auths_user" ON ("django_admin_log"."user_id" = "auths_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = '915b008a06b9406391807ca522830fca' ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=('915b008a06b9406391807ca522830fca',)
[2016-11-27 14:45:38] INFO [django.server:131] "GET /admin/ HTTP/1.1" 200 14135
[2016-11-27 14:45:38] INFO [django.server:131] "GET /static/admin/css/base.css HTTP/1.1" 200 15937
[2016-11-27 14:45:38] INFO [django.server:131] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 434
[2016-11-27 14:45:38] INFO [django.server:131] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[2016-11-27 14:45:39] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'market_service_apps.auths_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'market_service_apps.registro_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\registro_api\\urls.py'> (None:None) ^api/registro/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[2016-11-27 14:45:39] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[2016-11-27 14:45:39] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[2016-11-27 14:45:39] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[2016-11-27 14:45:39] INFO [django.server:131] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2016-11-27 14:45:39] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'market_service_apps.auths_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'market_service_apps.registro_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\registro_api\\urls.py'> (None:None) ^api/registro/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\\\MCR\\\\marketsoft\\\\ve_mcr\\\\lib\\\\site-packages\\\\django\\\\contrib\\\\admindocs\\\\urls.py'> (None:None) ^admin/doc/>"
[2016-11-27 14:45:39] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'market_service_apps.auths_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'market_service_apps.registro_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\registro_api\\urls.py'> (None:None) ^api/registro/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'rest_framework.urls' from 'D:\\\\MCR\\\\marketsoft\\\\ve_mcr\\\\lib\\\\site-packages\\\\rest_framework\\\\urls.py'> (rest_framework:rest_framework) ^api-auth/>"
[2016-11-27 14:45:39] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'market_service_apps.auths_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'market_service_apps.registro_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\registro_api\\urls.py'> (None:None) ^api/registro/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\\\MCR\\\\marketsoft\\\\ve_mcr\\\\lib\\\\site-packages\\\\oauth2_provider\\\\urls.py'> (None:oauth2_provider) ^o/>"
[2016-11-27 14:45:39] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'market_service_apps.auths_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'market_service_apps.registro_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\registro_api\\urls.py'> (None:None) ^api/registro/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'market_service_apps.auths_api.urls' from 'D:\\\\MCR\\\\marketsoft\\\\market_serve\\\\market_service_apps\\\\auths_api\\\\urls.py'> (None:None) ^api/auths/>"
[2016-11-27 14:45:39] INFO [django.server:131] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2016-11-27 14:45:39] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\MCR\\marketsoft\\ve_mcr\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'market_service_apps.auths_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'market_service_apps.registro_api.urls' from 'D:\\MCR\\marketsoft\\market_serve\\market_service_apps\\registro_api\\urls.py'> (None:None) ^api/registro/>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'market_service_apps.registro_api.urls' from 'D:\\\\MCR\\\\marketsoft\\\\market_serve\\\\market_service_apps\\\\registro_api\\\\urls.py'> (None:None) ^api/registro/>"
[2016-11-27 14:45:39] WARNING [django.request:152] Not Found: /favicon.ico
[2016-11-27 14:45:39] WARNING [django.server:131] "GET /favicon.ico HTTP/1.1" 404 2490
[2016-11-27 14:45:59] DEBUG [django.db.backends:90] (0.005) SELECT "auths_menu"."router_json" FROM "auths_menu" ORDER BY "auths_menu"."pos" ASC; args=()
[2016-11-27 14:45:59] INFO [django.server:131] "GET /api/auths/routers/ HTTP/1.1" 200 2
[2016-11-27 14:46:09] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_application" WHERE "oauth2_provider_application"."client_id" = '7kg3mZAQbOuc65ZmnDOkOcq6ouAVubhATreRa624'; args=('7kg3mZAQbOuc65ZmnDOkOcq6ouAVubhATreRa624',)
[2016-11-27 14:46:09] DEBUG [django.db.backends:90] (0.000) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."username" = 'admin'; args=('admin',)
[2016-11-27 14:46:09] DEBUG [django.db.backends:90] (0.001) BEGIN; args=None
[2016-11-27 14:46:09] DEBUG [django.db.backends:90] (0.001) INSERT INTO "oauth2_provider_accesstoken" ("user_id", "token", "application_id", "expires", "scope") VALUES ('915b008a06b9406391807ca522830fca', 'BaFwhgUlsBeWuhyyUXsFIqfdULy7FG', 1, '2016-11-28 08:46:09.691363', 'read write'); args=['915b008a06b9406391807ca522830fca', 'BaFwhgUlsBeWuhyyUXsFIqfdULy7FG', 1, '2016-11-28 08:46:09.691363', 'read write']
[2016-11-27 14:46:09] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 14:46:09] DEBUG [django.db.backends:90] (0.001) INSERT INTO "oauth2_provider_refreshtoken" ("user_id", "token", "application_id", "access_token_id") VALUES ('915b008a06b9406391807ca522830fca', '7qzKyCpfhHumm3CKFqALq4xe9WSJrP', 1, 21); args=['915b008a06b9406391807ca522830fca', '7qzKyCpfhHumm3CKFqALq4xe9WSJrP', 1, 21]
[2016-11-27 14:46:09] INFO [django.server:131] "POST /o/token/ HTTP/1.1" 200 169
[2016-11-27 14:46:10] INFO [django.server:131] "OPTIONS /api/auths/localuserinfo/ HTTP/1.1" 200 0
[2016-11-27 14:46:10] INFO [django.server:131] "OPTIONS /api/auths/usermenu/ HTTP/1.1" 200 0
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'BaFwhgUlsBeWuhyyUXsFIqfdULy7FG'; args=('BaFwhgUlsBeWuhyyUXsFIqfdULy7FG',)
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.000) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'BaFwhgUlsBeWuhyyUXsFIqfdULy7FG'; args=('BaFwhgUlsBeWuhyyUXsFIqfdULy7FG',)
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" INNER JOIN "auths_user_groups" ON ("auth_group"."id" = "auths_user_groups"."group_id") WHERE "auths_user_groups"."user_id" = '915b008a06b9406391807ca522830fca'; args=('915b008a06b9406391807ca522830fca',)
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "auths_user_user_permissions" ON ("auth_permission"."id" = "auths_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auths_user_user_permissions"."user_id" = '915b008a06b9406391807ca522830fca' ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=('915b008a06b9406391807ca522830fca',)
[2016-11-27 14:46:10] INFO [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 200 405
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'BaFwhgUlsBeWuhyyUXsFIqfdULy7FG'; args=('BaFwhgUlsBeWuhyyUXsFIqfdULy7FG',)
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'BaFwhgUlsBeWuhyyUXsFIqfdULy7FG'; args=('BaFwhgUlsBeWuhyyUXsFIqfdULy7FG',)
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.000) SELECT "auths_menu"."id" FROM "auths_menu" WHERE ("auths_menu"."id" IS NOT NULL AND "auths_menu"."is_active" = 1 AND "auths_menu"."module" = 'BACKEND') ORDER BY "auths_menu"."pos" ASC; args=(True, 'BACKEND')
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.001) SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = 'xek1cushjuhf07ly2pwir27dv3dps05r' LIMIT 1; args=('xek1cushjuhf07ly2pwir27dv3dps05r',)
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 14:46:10] DEBUG [django.db.backends:90] (0.001) INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT 'xek1cushjuhf07ly2pwir27dv3dps05r', 'Y2U1MDdhOTVhY2Y1M2EzOGYyOTc1YmE0OTQ4NTlmMWJkODNmMmEzMjp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 22:46:40.973951'; args=('xek1cushjuhf07ly2pwir27dv3dps05r', 'Y2U1MDdhOTVhY2Y1M2EzOGYyOTc1YmE0OTQ4NTlmMWJkODNmMmEzMjp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 22:46:40.973951')
[2016-11-27 14:46:10] INFO [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 200 11
[2016-11-27 21:40:48] DEBUG [django.db.backends:90] (0.002) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'figcln8g3oukkwuqylv6c0gc2bcu7o51' AND "django_session"."expire_date" > '2016-11-28 05:40:48.120979'); args=('figcln8g3oukkwuqylv6c0gc2bcu7o51', '2016-11-28 05:40:48.120979')
[2016-11-27 21:40:48] DEBUG [django.db.backends:90] (0.000) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."id" = '915b008a06b9406391807ca522830fca'; args=('915b008a06b9406391807ca522830fca',)
[2016-11-27 21:40:48] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'False': False, 'None': None}, {'request': <WSGIRequest: GET '/admin/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000121A9FFCCF8>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'INFO': 20, 'SUCCESS': 25, 'ERROR': 40, 'DEBUG': 10}, 'user': <SimpleLazyObject: <User: admin>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x00000121AA01DD90>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00000121A9FF7D68>}, {}, {'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D0BD68>, 'app_list': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8C7A630>, 'app_url': '/admin/auth/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCC50>, 'object_name': 'Group', 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCFD0>, 'object_name': 'Permission', 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB940>, 'object_name': 'HierarchyType', 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFC9E8>, 'object_name': 'Hierarchy', 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB6A0>, 'object_name': 'Menu', 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFC278>, 'object_name': 'Person', 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDF4A8>, 'object_name': 'UserHierarchyGroup', 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCF28>, 'object_name': 'UserHierarchyPermission', 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB7B8>, 'object_name': 'User', 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D1C9E8>, 'app_url': '/admin/contenttypes/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCB70>, 'object_name': 'ContentType', 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFC9B0>, 'object_name': 'AccessToken', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCA58>, 'object_name': 'Application', 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCE80>, 'object_name': 'Grant', 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCEB8>, 'object_name': 'RefreshToken', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'has_module_perms': True, 'app_label': 'registro', 'name': 'Registro', 'app_url': '/admin/registro/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': 'Clientes', 'object_name': 'Cliente', 'admin_url': '/admin/registro/cliente/', 'add_url': '/admin/registro/cliente/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB630>, 'object_name': 'Distribuidor', 'admin_url': '/admin/registro/distribuidor/', 'add_url': '/admin/registro/distribuidor/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCB38>, 'object_name': 'Marca', 'admin_url': '/admin/registro/marca/', 'add_url': '/admin/registro/marca/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB780>, 'object_name': 'Producto', 'admin_url': '/admin/registro/producto/', 'add_url': '/admin/registro/producto/add/'}]}], 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D03B38>, 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D03A90>, 'has_permission': True, 'available_apps': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8C7A630>, 'app_url': '/admin/auth/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBAC8>, 'object_name': 'Group', 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBB70>, 'object_name': 'Permission', 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBDA0>, 'object_name': 'HierarchyType', 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB8D0>, 'object_name': 'Hierarchy', 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBDD8>, 'object_name': 'Menu', 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB9B0>, 'object_name': 'Person', 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBCC0>, 'object_name': 'UserHierarchyGroup', 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB9E8>, 'object_name': 'UserHierarchyPermission', 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBD30>, 'object_name': 'User', 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D1C9E8>, 'app_url': '/admin/contenttypes/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBCF8>, 'object_name': 'ContentType', 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBB00>, 'object_name': 'AccessToken', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBBE0>, 'object_name': 'Application', 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBBA8>, 'object_name': 'Grant', 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBC50>, 'object_name': 'RefreshToken', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'has_module_perms': True, 'app_label': 'registro', 'name': 'Registro', 'app_url': '/admin/registro/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': 'Clientes', 'object_name': 'Cliente', 'admin_url': '/admin/registro/cliente/', 'add_url': '/admin/registro/cliente/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBD68>, 'object_name': 'Distribuidor', 'admin_url': '/admin/registro/distribuidor/', 'add_url': '/admin/registro/distribuidor/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBB38>, 'object_name': 'Marca', 'admin_url': '/admin/registro/marca/', 'add_url': '/admin/registro/marca/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBF98>, 'object_name': 'Producto', 'admin_url': '/admin/registro/producto/', 'add_url': '/admin/registro/producto/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'site_url': '/', 'LANGUAGE_BIDI': False}]"
[2016-11-27 21:40:48] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCR\marketsoft\ve_mcr\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'True': True, 'False': False, 'None': None}, {'request': <WSGIRequest: GET '/admin/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000121A9FFCCF8>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'INFO': 20, 'SUCCESS': 25, 'ERROR': 40, 'DEBUG': 10}, 'user': <SimpleLazyObject: <User: admin>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x00000121AA01DD90>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00000121A9FF7D68>}, {}, {'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D0BD68>, 'app_list': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8C7A630>, 'app_url': '/admin/auth/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCC50>, 'object_name': 'Group', 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCFD0>, 'object_name': 'Permission', 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB940>, 'object_name': 'HierarchyType', 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFC9E8>, 'object_name': 'Hierarchy', 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB6A0>, 'object_name': 'Menu', 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFC278>, 'object_name': 'Person', 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDF4A8>, 'object_name': 'UserHierarchyGroup', 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCF28>, 'object_name': 'UserHierarchyPermission', 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB7B8>, 'object_name': 'User', 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D1C9E8>, 'app_url': '/admin/contenttypes/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCB70>, 'object_name': 'ContentType', 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFC9B0>, 'object_name': 'AccessToken', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCA58>, 'object_name': 'Application', 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCE80>, 'object_name': 'Grant', 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCEB8>, 'object_name': 'RefreshToken', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'has_module_perms': True, 'app_label': 'registro', 'name': 'Registro', 'app_url': '/admin/registro/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': 'Clientes', 'object_name': 'Cliente', 'admin_url': '/admin/registro/cliente/', 'add_url': '/admin/registro/cliente/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB630>, 'object_name': 'Distribuidor', 'admin_url': '/admin/registro/distribuidor/', 'add_url': '/admin/registro/distribuidor/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FFCB38>, 'object_name': 'Marca', 'admin_url': '/admin/registro/marca/', 'add_url': '/admin/registro/marca/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB780>, 'object_name': 'Producto', 'admin_url': '/admin/registro/producto/', 'add_url': '/admin/registro/producto/add/'}]}], 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D03B38>, 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D03A90>, 'has_permission': True, 'available_apps': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8C7A630>, 'app_url': '/admin/auth/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBAC8>, 'object_name': 'Group', 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBB70>, 'object_name': 'Permission', 'admin_url': '/admin/auth/permission/', 'add_url': '/admin/auth/permission/add/'}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBDA0>, 'object_name': 'HierarchyType', 'admin_url': '/admin/auths/hierarchytype/', 'add_url': '/admin/auths/hierarchytype/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB8D0>, 'object_name': 'Hierarchy', 'admin_url': '/admin/auths/hierarchy/', 'add_url': '/admin/auths/hierarchy/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBDD8>, 'object_name': 'Menu', 'admin_url': '/admin/auths/menu/', 'add_url': '/admin/auths/menu/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB9B0>, 'object_name': 'Person', 'admin_url': '/admin/auths/person/', 'add_url': '/admin/auths/person/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBCC0>, 'object_name': 'UserHierarchyGroup', 'admin_url': '/admin/auths/userhierarchygroup/', 'add_url': '/admin/auths/userhierarchygroup/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDB9E8>, 'object_name': 'UserHierarchyPermission', 'admin_url': '/admin/auths/userhierarchypermission/', 'add_url': '/admin/auths/userhierarchypermission/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBD30>, 'object_name': 'User', 'admin_url': '/admin/auths/user/', 'add_url': '/admin/auths/user/add/'}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A8D1C9E8>, 'app_url': '/admin/contenttypes/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBCF8>, 'object_name': 'ContentType', 'admin_url': '/admin/contenttypes/contenttype/', 'add_url': '/admin/contenttypes/contenttype/add/'}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBB00>, 'object_name': 'AccessToken', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'add_url': '/admin/oauth2_provider/accesstoken/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBBE0>, 'object_name': 'Application', 'admin_url': '/admin/oauth2_provider/application/', 'add_url': '/admin/oauth2_provider/application/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBBA8>, 'object_name': 'Grant', 'admin_url': '/admin/oauth2_provider/grant/', 'add_url': '/admin/oauth2_provider/grant/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBC50>, 'object_name': 'RefreshToken', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'add_url': '/admin/oauth2_provider/refreshtoken/add/'}]}, {'has_module_perms': True, 'app_label': 'registro', 'name': 'Registro', 'app_url': '/admin/registro/', 'models': [{'perms': {'add': True, 'delete': True, 'change': True}, 'name': 'Clientes', 'object_name': 'Cliente', 'admin_url': '/admin/registro/cliente/', 'add_url': '/admin/registro/cliente/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBD68>, 'object_name': 'Distribuidor', 'admin_url': '/admin/registro/distribuidor/', 'add_url': '/admin/registro/distribuidor/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBB38>, 'object_name': 'Marca', 'admin_url': '/admin/registro/marca/', 'add_url': '/admin/registro/marca/add/'}, {'perms': {'add': True, 'delete': True, 'change': True}, 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00000121A9FDBF98>, 'object_name': 'Producto', 'admin_url': '/admin/registro/producto/', 'add_url': '/admin/registro/producto/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'site_url': '/', 'LANGUAGE_BIDI': False}]"
[2016-11-27 21:40:48] DEBUG [django.db.backends:90] (0.001) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auths_user" ON ("django_admin_log"."user_id" = "auths_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = '915b008a06b9406391807ca522830fca' ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=('915b008a06b9406391807ca522830fca',)
[2016-11-27 21:40:48] INFO [django.server:131] "GET /admin/ HTTP/1.1" 200 14135
